#server:
#  port: 8091
#
#
#
dubbo:
  registry:
    address: spring-cloud://localhost
  cloud:
    subscribed-services:  blog-provider
  application:
    qos-accept-foreign-ip: false
    qos-enable: false
    qos-port: 44555

#
#spring:
#  cloud:
#    nacos:
#      discovery:
#        server-addr: 127.0.0.1:8848
#        enabled: true
#        register-enabled: true
#      config:
#        server-addr: 127.0.0.1:8848
#  application:
#    name: blog-web


