server:
  port: 8092



dubbo:
  registry:
    address: spring-cloud://localhost
  cloud:
    subscribed-services:  blog-provider

spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        enabled: true
        register-enabled: true

  application:
    name: blog-web

